/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-tertiary-fixed": "#2d1600",
        "inverse-surface": "#dae2fd",
        "surface-slate-800": "#1e293b",
        "surface-container-high": "#222a3d",
        "tertiary": "#ffb873",
        "on-background": "#dae2fd",
        "text-slate-100": "#f8fafc",
        "on-surface-variant": "#bcc9cd",
        "on-surface": "#dae2fd",
        "secondary-fixed": "#e1e0ff",
        "outline": "#869397",
        "on-primary-fixed-variant": "#004e5c",
        "inverse-on-surface": "#283044",
        "on-tertiary": "#4b2800",
        "surface-container-low": "#131b2e",
        "bg-slate-900": "#0f172a",
        "surface-container-highest": "#2d3449",
        "tertiary-fixed": "#ffdcbf",
        "secondary": "#c0c1ff",
        "surface-dim": "#0b1326",
        "on-primary": "#003640",
        "border-slate-800": "#1e293b",
        "secondary-fixed-dim": "#c0c1ff",
        "error": "#ffb4ab",
        "tertiary-container": "#e89337",
        "background": "#0b1326",
        "tertiary-fixed-dim": "#ffb873",
        "on-secondary-container": "#b0b2ff",
        "error-container": "#93000a",
        "on-secondary": "#1000a9",
        "surface-variant": "#2d3449",
        "on-primary-container": "#00424f",
        "outline-variant": "#3d494c",
        "on-error": "#690005",
        "surface": "#0b1326",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "text-slate-400": "#94a3b8",
        "surface-tint": "#4cd7f6",
        "surface-bright": "#31394d",
        "primary-container": "#06b6d4",
        "on-secondary-fixed": "#07006c",
        "inverse-primary": "#00687a",
        "on-tertiary-container": "#5b3200",
        "primary": "#4cd7f6",
        "on-secondary-fixed-variant": "#2f2ebe",
        "primary-fixed-dim": "#4cd7f6",
        "secondary-container": "#3131c0",
        "primary-fixed": "#acedff",
        "on-primary-fixed": "#001f26",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "max-width": "1200px",
        "margin-mobile": "16px",
        base: "4px",
        gutter: "24px",
      },
      maxWidth: {
        page: "1200px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Geist", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["\"JetBrains Mono\"", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      keyframes: {
        "pulse-ring": {
          "0%": { transform: "scale(1)", opacity: "0.7" },
          "100%": { transform: "scale(2.4)", opacity: "0" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 1.8s cubic-bezier(0.2, 0.6, 0.4, 1) infinite",
      },
    },
  },
  plugins: [],
};
